// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhizomeqdmmbaxrmpigw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoaXpvbWVxZG1tYmF4cm1waWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMDcxMDksImV4cCI6MjA0OTU4MzEwOX0.claNFM-Kj2d5YbFO1z7OYvc4DuxMPNV3Ct5yS_E4YhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);